import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "~/utils/api";

export default function Home() {
  const hello = trpc.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>FormTazk</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>Pipayo</h1>
      </main>
    </>
  );
}