
import { GetServerSideProps } from "next";
import Head from "next/head";
import { SimpleCTA } from "~/components/SimpleCTA";
import { getServerAuthSession } from "~/server/auth";

import { trpc } from "~/utils/api";

export default function Home() {
  const hello = trpc.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>FormTazk</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col items-center justify-center">
        <SimpleCTA />
      </main>
    </>
  );
}


export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx)
  if (!session)
    return {
      props: {},
      redirect: {
        destination: '/login',
        permanent: false,

      }
    }

  return {
    props: {}
  }
}