export const communes: Array<string> = [
    "ALGARROBO",
    "ALHUE",
    "ALTO BIOBIO",
    "ALTO DEL CARMEN",
    "ALTO HOSPICIO",
    "ANCUD",
    "ANDACOLLO",
    "ANTARTICA",
    "ANTOFAGASTA",
    "ANTUCO",
    "ARAUCO",
    "ARICA",
    "AYSEN",
    "BUIN",
    "BULNES",
    "CABO DE HORNOS(EX-NAVARINO)",
    "CABILDO",
    "CABRERO",
    "CALAMA",
    "CALBUCO",
    "CALDERA",
    "CALERA",
    "CALERA DE TANGO",
    "CALLE LARGA",
    "CAMARONES",
    "CAMIÑA",
    "CANELA",
    "CARAHUE",
    "CARTAGENA",
    "CASABLANCA",
    "CASTRO",
    "CATEMU",
    "CAUQUENES",
    "CERRO NAVIA",
    "CERRILLOS",
    "CHAITEN",
    "CHANC0",
    "CHAÑARAL",
    "CHEPICA",
    "CHIGUAYANTE",
    "CHILE CHICO",
    "CHILLAN",
    "CHILLAN VIEJO",
    "CHIMBARONGO",
    "CHOLCHOL",
    "CHONCHI",
    "CISNES",
    "COBQUECURA",
    "CODEGUA",
    "COELEMU",
    "COIHUECO",
    "COINCO",
    "COLBUN",
    "COLCHANE",
    "COLINA",
    "COLTAUCO",
    "COMBARBALA",
    "CONCEPCION",
    "CONCHALI",
    "CONCON",
    "CONSTITUCION",
    "CONTULMO",
    "COPIAPO",
    "COQUIMBO",
    "CORONEL",
    "CORRAL",
    "CUREPTO",
    "CURACAUTIN",
    "CURACO DE VELEZ",
    "CURANILAHUE",
    "CURACAVI",
    "CURICO",
    "DALCAHUE",
    "DIEGO DE ALMAGRO",
    "DOÑIHUE",
    "EL BOSQUE",
    "EL CARMEN",
    "EL MONTE",
    "EL QUISCO",
    "EL TABO",
    "EMPEDRADO",
    "ERCILLA",
    "ESTACION CENTRAL",
    "FLORIDA",
    "FREIRE",
    "FREIRINA",
    "FRESIA",
    "FRUTILLAR",
    "FUTALEUFU",
    "FUTRONO",
    "GALVARINO",
    "GENERAL LAGOS",
    "GORBEA",
    "GRANEROS",
    "GUAITECAS",
    "HIJUELAS",
    "HUALAIHUE",
    "HUALAÑE",
    "HUALPEN",
    "HUALQUI",
    "HUARA",
    "HUECHURABA",
    "HUASCO",
    "ILLAPEL",
    "INDEPENDENCIA",
    "IQUIQUE",
    "ISLA DE MAIPO",
    "ISLA DE PASCUA",
    "JUAN FERNANDEZ",
    "LAGO RANCO",
    "LAGO VERDE",
    "LA CISTERNA",
    "LA CRUZ",
    "LA ESTRELLA",
    "LA FLORIDA",
    "LA GRANJA",
    "LA HIGUERA",
    "LAJA",
    "LA LIGUA",
    "LA PINTANA",
    "LA REINA",
    "LA SERENA",
    "LA UNION",
    "LANCO",
    "LAMP0",
    "LAS CABRAS",
    "LAS CONDES",
    "LEBU",
    "LICANTEN",
    "LIMACHE",
    "LINARES",
    "LITUECHE",
    "LLAILLAY",
    "LLANQUIHUE",
    "LO BARNECHEA",
    "LO ESPEJO",
    "LOLOL",
    "LO PRADO",
    "LONGAVI",
    "LONCOCHE",
    "LONQUIMAY",
    "LOS ALAMOS",
    "LOS ANDES",
    "LOS ANGELES",
    "LOS LAGOS",
    "LOS MUERMOS",
    "LOS SAUCES",
    "LOS VILOS",
    "LOTA",
    "LUMACO",
    "MACUL",
    "MAFIL",
    "MAIPU",
    "MALL0A",
    "MARCHIGUE",
    "MARIA ELENA",
    "MARIA PINTO",
    "MARIQUINA",
    "MELIPEUCO",
    "MELIPILLA",
    "MEJILLONES",
    "MOSTAZAL",
    "MONTE PATRIA",
    "MOLINA",
    "MULCHEN",
    "NACIMIENTO",
    "NANCAGUA",
    "NATALES",
    "NAVIDAD",
    "NEGRETE",
    "NINHUE",
    "NOGALES",
    "NUEVA IMPERIAL",
    "ÑIQUEN",
    "ÑUÑOA",
    "O'HIGGINS",
    "OLIVAR",
    "OLMUE",
    "OLLAGUE",
    "OVALLE",
    "PADRE HURTADO",
    "PADRE LAS CASAS",
    "PAIGUANO",
    "PAILLACO",
    "PAINE",
    "PALENA",
    "PALMILLA",
    "PANQUEHUE",
    "PANGUIPULLI",
    "PAPUDO",
    "PAREDONES",
    "PARRAL",
    "PEDRO AGUIRRE CERDA",
    "PEMUCO",
    "PENCAHUE",
    "PENCO",
    "PEÑAFLOR",
    "PEÑALOLEN",
    "PERALILLO",
    "PERQUENCO",
    "PETORCA",
    "PICA",
    "PICHIDEGUA",
    "PICHILEMU",
    "PINTO",
    "PIRQUE",
    "PLACILLA",
    "PORTEZUELO",
    "PORVENIR",
    "POZO ALMONTE",
    "PRIMAVERA",
    "PROVIDENCIA",
    "PUCHUNCAVI",
    "PUCON",
    "PUDAHUEL",
    "PUENTE ALTO",
    "PUERTO MONTT",
    "PUERTO OCTAY",
    "PUERTO VARAS",
    "PUQUELDON",
    "PUNITAQUI",
    "PUNTA ARENAS",
    "PUREN",
    "PURRANQUE",
    "PUYEHUE",
    "PUTAENDO",
    "PUTRE",
    "QUEILEN",
    "QUELLON",
    "QUEMCHI",
    "QUILACO",
    "QUILICURA",
    "QUILLON",
    "QUILLOTA",
    "QUILPUE",
    "QUINCHAO",
    "QUINTA DE TILCOCO",
    "QUINTA NORMAL",
    "QUINTERO",
    "QUIRIHUE",
    "RANCAGUA",
    "RANQUIL",
    "RAUCO",
    "RECOLETA",
    "RENCA",
    "RENGO",
    "REQUINOA",
    "RETIRO",
    "RINCONADA",
    "RIO BUENO",
    "RIO CLARO",
    "RIO HURTADO",
    "RIO IBAÑEZ",
    "RIO NEGRO",
    "RIO VERDE",
    "ROMERAL",
    "SAAVEDRA",
    "SAGRADA FAMILIA",
    "SALAMANCA",
    "SAN ANTONIO",
    "SAN BERNARDO",
    "SAN CARLOS",
    "SAN CLEMENTE",
    "SAN ESTEBAN",
    "SAN FABIAN",
    "SAN FELIPE",
    "SAN FERNANDO",
    "SAN GREGORIO",
    "SAN IGNACIO",
    "SAN JAVIER",
    "SAN JOAQUIN",
    "SAN JOSE DE MAIPO",
    "SAN JUAN DE LA COSTA",
    "SAN MIGUEL",
    "SAN NICOLAS",
    "SAN PABLO",
    "SAN PEDRO",
    "SAN PEDRO DE ATACAMA",
    "SAN PEDRO DE LA PAZ",
    "SAN RAFAEL",
    "SAN RAMON",
    "SANTA BARBARA",
    "SANTA CRUZ",
    "SANTA JUANA",
    "SANTA MARIA",
    "SANTO DOMINGO",
    "SANTIAGO",
    "SIERRA GORDA",
    "TALAGANTE",
    "TALCA",
    "TALCAHUANO",
    "TALTAL",
    "TENO",
    "TEODORO SCHMIDT",
    "TILC0",
    "TIMAUKEL",
    "TIRUA",
    "TOCOPILLA",
    "TOLTEN",
    "TOME",
    "TORRES DEL PAINE",
    "TORTEL",
    "TREHUACO",
    "TUCAPEL",
    "VALLENAR",
    "VALDIVIA",
    "VALPARAISO",
    "VICHUQUEN",
    "VICUÑA",
    "VICTORIA",
    "VILLA ALEGRE",
    "VILLA ALEMANA",
    "VILCUN",
    "VILLARRICA",
    "VIÑA DEL MAR",
    "VITACURA",
    "YERBAS BUENAS",
    "YUMBEL",
    "YUNGAY",
    "ZAPALLAR"
]