export const regions: Array<string> = [
    "DE ANTOFAGASTA",
    "DE ARICA Y PARINACOTA",
    "DE AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO",
    "DE ATACAMA",
    "DE COQUIMBO",
    "DE LA ARAUCANIA",
    "DE LOS LAGOS",
    "DE LOS RIOS",
    "DE MAGALLANES Y DE LA ANTARTICA CHILENA",
    "DE ÑUBLE",
    "DE TARAPACA",
    "DE VALPARAISO",
    "DEL BIOBIO",
    "DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",
    "DEL MAULE",
    "METROPOLITANA DE SANTIAGO"
]