export const tags: Array<{ value: string, name: string }> = [
    { value: 'dirigente-social', name: 'Dirigente Social' },
    { value: 'profesional', name: 'Profesional' },
    { value: 'tecnico', name: 'Técnico' },
    { value: 'operativo-social', name: 'Operativo Social' },
    { value: 'operativo-salud', name: 'Operativo Salud' },
    { value: 'bingo', name: 'Bingo' },
    { value: 'ayuda-social', name: 'Ayuda Social' },
    { value: 'militante', name: 'Militante' },
    { value: 'simpatizantes', name: 'Simpatizantes' },
    { value: 'techo', name: 'Techo' },
    { value: 'casa-a-casa', name: 'Casa a Casa' },
    { value: 'sector-centro', name: 'Sector Centro' },
    { value: 'sector-norte', name: 'Sector Norte' },
    { value: 'sector-sur', name: 'Sector Sur' },
    { value: 'sector-oriente', name: 'Sector Oriente' },
    { value: 'sector-poniente', name: 'Sector Poniente' },
    { value: 'funcionario', name: 'Funcionario' },
    { value: 'uniformado-en-retiro', name: 'Uniformado en Retiro' },
    { value: 'rn', name: 'RN' },
    { value: 'republicano', name: 'Republicano' },
    { value: 'frente-amplio', name: 'Frente Amplio' },
    { value: 'dc', name: 'DC' },
    { value: 'feria', name: 'Feria' },
    { value: 'locatario', name: 'Locatario' },
    { value: 'colectivero', name: 'Colectivero' },
    { value: 'colero', name: 'Colero' },
    { value: 'pyme', name: 'PYME' },
    { value: 'empresario', name: 'Empresario' }
].sort((a, b) => a.name.localeCompare(b.name))
